/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package time

import java.io.IOException

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val processBuilder = ProcessBuilder()
    processBuilder.command(args.toMutableList())
    val start = System.nanoTime()
    try {
        val process = processBuilder.start()
        val ret = process.waitFor()
        val result = System.nanoTime() - start
        println(process.inputStream.bufferedReader().use { it.readText() })
        println("Time: ${result.toDouble() / 1000000000} seconds")
        System.exit(ret)
    } catch (e: IOException) {
        println("Command not found: ${args[0]}")
        System.exit(127)
    }

}
